# Generated by Django 3.2.16 on 2023-08-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Haзвание')),
                ('anons', models.CharField(max_length=250, verbose_name='AHOHC')),
                ('full_text', models.TextField(verbose_name='Cтатья')),
                ('date', models.DateTimeField(verbose_name='Дarа публикии')),
            ],
        ),
    ]
